# Generated by Django 6.0 on 2026-01-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], default='Básico', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Habilidades',
            },
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'verbose_name_plural': 'Educación'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfil'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='cv_pdf',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='dni',
            field=models.CharField(default='', max_length=10, verbose_name='Cédula/DNI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sector',
            field=models.CharField(default='', max_length=100, verbose_name='Barrio/Sector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, help_text='Ej: Django, IoT, ESP32', max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío si trabaja actualmente', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='resumen',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link del Proyecto/GitHub'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
