# Generated by Django 6.0 on 2026-01-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_habilidad_alter_educacion_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='github',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tecnologias',
        ),
        migrations.RemoveField(
            model_name='reconocimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='email',
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cédula/DNI'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio/Sector'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
