# Generated by Django 6.0 on 2026-01-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_delete_habilidad_remove_perfil_github_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacion',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='educacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción corta'),
        ),
    ]
