# Generated by Django 5.1.4 on 2026-02-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_curso_alter_certificado_id_alter_educacion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='archivo_extra',
            field=models.FileField(blank=True, null=True, upload_to='cursos/extras/', verbose_name='Archivo Extra'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='vista_previa',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/previews/', verbose_name='Imagen de Vista Previa'),
        ),
    ]
