# Generated by Django 5.1.4 on 2026-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_certificado_perfil_curso_perfil_educacion_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='experiencia/archivos/', verbose_name='Constancia/Archivo (PDF)'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='experiencia/logos/', verbose_name='Logo Empresa / Imagen'),
        ),
    ]
